server:
  port: 9999

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: policy-service
          uri: lb://policy-service
          predicates:
            - Path=/api/policies/**

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**

        - id: claims-service
          uri: lb://claims-service
          predicates:
            - Path=/api/claims/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notify/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
