server:
  port: 8082

spring:
  application:
    name: customer-service

  config:
    import: optional:configserver:http://localhost:8888  #Fetching configuration from repository

  datasource:
    url: jdbc:mysql://localhost:3306/embeded_insurance
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
